#ifndef __WINE_AUTHORS_H
#define __WINE_AUTHORS_H

static const char * const SHELL_People[] =
{
    "Herwig Bauernfeind",
    "Christoph Bratschi",
    "Oliver Braun",
    "Edgar Buerkle",
    "Yuri Dario",
    "Przemyslaw Dobrowolski",
    "Daniela Engert",
    "Peter Fitzsimmons",
    "Platon Fomichev",
    "Dmitry Froloff",
    "Adrian Gschwend",
    "Jeroen van den Horn",
    "Patrick Haller",
    "Achim Hasenmueller",
    "KO Myung-Hun",
    "Dmitriy Kuminov",
    "Kevin Langman",
    "Bart van Leeuwen",
    "Sander van Leeuwen",
    "Felix Maschek",
    "Chris McKillop",
    "Nenad Milenkovic",
    "Markus Montkowski",
    "Michal Necasek",
    "Ondrej Necasek",
    "Knut Stange Osmundsen",
    "Vitali E. Pelenyov",
    "Rene Pronk",
    "David Raison",
    "Silvan Scherrer",
    "Joerg Sievers",
    "Joerg Skottke",
    "Kai Sommerfeld",
    "Dietrich Teickner",
    "Carsten Tenbrink",
    "Vit Timchishin",
    "Joel Troster",
    "Shingo Tsuda",
    "Vince Vielhaber",
    "Jens Wiessner",
    "Chris Wohlgemuth",
    "<<< all the WINE people >>>",
    NULL
};

#endif  /* __WINE_AUTHORS_H */
