## @file
# DCIMAN32 library
#

SUB_DEPTH = ../..
include $(KBUILD_PATH)/subheader.kmk

$(call odin_implib,dciman32)

DLLS               += dciman32
dciman32_TEMPLATE   = OdinSimpleDLL

dciman32_SOURCES    = \
    dciman32.cpp \
    dcimanrsrc.orc \
    dciman32.def

dciman32_LIBS       = \
    $(PATH_STAGE_LIB)/kernel32.lib \
    $(PATH_STAGE_LIB)/gdi32.lib

include $(FILE_KBUILD_SUB_FOOTER)
