## @file
# DPLAY library
#

SUB_DEPTH = ../..
include $(KBUILD_PATH)/subheader.kmk

$(call odin_implib,dplay)

DLLS               += dplay
dplay_TEMPLATE      = OdinSimpleDLL

dplay_SOURCES       = \
    dplay.cpp \
    dplayrsrc.orc \
    dplay.def

dplay_LIBS          = \
    $(PATH_STAGE_LIB)/kernel32.lib \
    $(PATH_STAGE_LIB)/advapi32.lib \
    $(PATH_STAGE_LIB)/ole32.lib

include $(FILE_KBUILD_SUB_FOOTER)
