## @file
#

SUB_DEPTH = ../..
include $(KBUILD_PATH)/subheader.kmk

PROGRAMS           += encodings
encodings_TEMPLATE  = OdinTestApp

encodings_SOURCES   = \
    test.c

encodings_LIBS      = \
    $(PATH_STAGE_LIB)/kernel32.lib \
    $(PATH_STAGE_LIB)/user32.lib

include $(FILE_KBUILD_SUB_FOOTER)
