## @file
# IMPDEF makefile.
#

SUB_DEPTH = ../..
include $(KBUILD_PATH)/subheader.kmk

BLDPROGS           += impdef
impdef_TEMPLATE     = OdinBin

# @todo: the need of this for BLDPROGS looks like a kBuild bug to me
impdef_INST         = bin/
impdef_INSTTYPE     = stage

impdef_INCS         = \
    ../common

impdef_SOURCES      = \
    ImpDef.cpp \
    ImpDef.def

impdef_LIBS         = \
    $(PATH_STAGE_LIB)/common.lib

include $(FILE_KBUILD_SUB_FOOTER)
