## @file
# PSAPI library
#

SUB_DEPTH = ../..
include $(KBUILD_PATH)/subheader.kmk

$(call odin_implib,psapi)

DLLS               += psapi
psapi_TEMPLATE      = OdinSimpleDLL

psapi_SOURCES       = \
    psapi.cpp \
    psapirsrc.orc \
    psapi.def

psapi_LIBS          = \
    $(PATH_STAGE_LIB)/kernel32.lib

include $(FILE_KBUILD_SUB_FOOTER)
