## @file
#

SUB_DEPTH = ../..
include $(KBUILD_PATH)/subheader.kmk

PROGRAMS           += threads
threads_TEMPLATE    = OdinTestApp
threads_SOURCES     = threads.c
threads_LIBS        = $(PATH_STAGE_LIB)/libwrap.lib \
                      $(PATH_STAGE_LIB)/kernel32.lib \
                      $(PATH_STAGE_LIB)/user32.lib

include $(FILE_KBUILD_SUB_FOOTER)
