## @file
# ODININST makefile.
#

SUB_DEPTH = ../..
include $(KBUILD_PATH)/subheader.kmk

PROGRAMS           += odininst
odininst_TEMPLATE   = OdinApp

odininst_SOURCES    = \
    odininst.cpp \
    regapi.c \
    tz.c \
    odininst.def

odininst_LIBS      += \
    $(PATH_STAGE_LIB)/kernel32.lib \
    $(PATH_STAGE_LIB)/user32.lib \
    $(PATH_STAGE_LIB)/advapi32.lib

include $(FILE_KBUILD_SUB_FOOTER)
