## @file
# QUARTZ library
#

SUB_DEPTH = ../..
include $(KBUILD_PATH)/subheader.kmk

#$(call odin_implib,quartz)

DLLS               += quartz
quartz_TEMPLATE     = OdinSimpleDLL

quartz_DEFS         = ICOM_CINTERFACE CINTERFACE

quartz_SOURCES      = \
    main.c \
    quartzrsrc.orc \
    quartz.def

quartz_LIBS         = \
    $(PATH_STAGE_LIB)/kernel32.lib

include $(FILE_KBUILD_SUB_FOOTER)
