## @file
# OLESVR32 library
#

SUB_DEPTH = ../..
include $(KBUILD_PATH)/subheader.kmk

$(call odin_implib,olesvr32)

DLLS               += olesvr32
olesvr32_TEMPLATE   = OdinSimpleDLL

olesvr32_SOURCES    = \
    olesvr32.cpp \
    olesvr32rsrc.orc \
    olesvr32.def

olesvr32_LIBS       = \
    $(PATH_STAGE_LIB)/kernel32.lib

include $(FILE_KBUILD_SUB_FOOTER)
