## @file
#

SUB_DEPTH = ../../..
include $(KBUILD_PATH)/subheader.kmk

PROGRAMS           += fileopen
fileopen_TEMPLATE   = OdinTestApp

fileopen_SOURCES    = \
    fileopen.cpp

fileopen_DEFS       = UNICODE

fileopen_LIBS       = \
    $(PATH_STAGE_LIB)/kernel32.lib \
    $(PATH_STAGE_LIB)/comdlg32.lib \
    $(PATH_STAGE_LIB)/user32.lib

include $(FILE_KBUILD_SUB_FOOTER)
