## @file
# LZ32 library
#

SUB_DEPTH = ../..
include $(KBUILD_PATH)/subheader.kmk

$(call odin_implib,lz32)

DLLS               += lz32
lz32_TEMPLATE       = OdinSimpleDLL

lz32_SOURCES        = \
    lz32.cpp \
    lz32rsrc.orc \
    lz32.def

lz32_LIBS           = \
    $(PATH_STAGE_LIB)/kernel32.lib

include $(FILE_KBUILD_SUB_FOOTER)
