## @file
# RASAPI32 library
#

SUB_DEPTH = ../..
include $(KBUILD_PATH)/subheader.kmk

$(call odin_implib,rasapi32)

DLLS               += rasapi32
rasapi32_TEMPLATE   = OdinSimpleDLL

rasapi32_SOURCES    = \
    rasapi32.cpp \
    rasapi32rsrc.orc \
    rasapi32.def

rasapi32_LIBS       = \
    $(PATH_STAGE_LIB)/kernel32.lib

include $(FILE_KBUILD_SUB_FOOTER)
