#include <odin.h>
#include <odinwrap.h>
#include <os2sel.h>

#include <os2win.h>
#include <winreg.h>
#include <winnt.h>
#include <wincon.h>
#include <winthunk.h>
#include <winnls.h>
#include <ntddk.h>
#include "ole32.h"
#include <heapstring.h>
#include "wine/obj_errorinfo.h"
#include "wine/obj_oleaut.h"

#define DBGWRAP_MODULE "OLE32"
#include <dbgwrap.h>


DEBUGWRAP16(BindMoniker)
DEBUGWRAP8(CLSIDFromProgID)
DEBUGWRAP8(CLSIDFromString)
DEBUGWRAP0(CoBuildVersion)
DEBUGWRAP8(CoCreateFreeThreadedMarshaler)
DEBUGWRAP4(CoCreateGuid)
DEBUGWRAP20(CoCreateInstance)
DEBUGWRAP8(CoDisconnectObject)
DEBUGWRAP12(CoDosDateTimeToFileTime)
DEBUGWRAP4(CoFileTimeNow)
DEBUGWRAP12(CoFileTimeToDosDateTime)
DEBUGWRAP0_NORET(CoFreeAllLibraries)
DEBUGWRAP4(CoFreeLibrary)
DEBUGWRAP0_NORET(CoFreeUnusedLibraries)
NODEF_DEBUGWRAP0(CoGetCallerTID)
DEBUGWRAP20(CoGetClassObject)
NODEF_DEBUGWRAP0(CoGetCurrentLogicalThreadId)
DEBUGWRAP0(CoGetCurrentProcess)
DEBUGWRAP12(CoGetInterfaceAndReleaseStream)
DEBUGWRAP8(CoGetMalloc)
DEBUGWRAP24(CoGetMarshalSizeMax)
DEBUGWRAP8(CoGetPSClsid)
DEBUGWRAP24(CoGetStandardMarshal)
NODEF_DEBUGWRAP0(CoGetState)
DEBUGWRAP8(CoGetTreatAsClass)
DEBUGWRAP4(CoInitialize)
NODEF_DEBUGWRAP8(CoInitializeWOW)
DEBUGWRAP4(CoIsHandlerConnected)
DEBUGWRAP4(CoIsOle1Class)
DEBUGWRAP8(CoLoadLibrary)
DEBUGWRAP12(CoLockObjectExternal)
DEBUGWRAP8(CoMarshalHresult)
DEBUGWRAP12(CoMarshalInterThreadInterfaceInStream)
DEBUGWRAP24(CoMarshalInterface)
NODEF_DEBUGWRAP0(CoQueryReleaseObject)
DEBUGWRAP20(CoRegisterClassObject)
DEBUGWRAP4(CoRegisterMallocSpy)
DEBUGWRAP8(CoRegisterMessageFilter)
DEBUGWRAP4(CoReleaseMarshalData)
DEBUGWRAP4(CoRevokeClassObject)
DEBUGWRAP0(CoRevokeMallocSpy)
NODEF_DEBUGWRAP4(CoSetState)
DEBUGWRAP4(CoTaskMemAlloc)
DEBUGWRAP4(CoTaskMemFree)
DEBUGWRAP8(CoTaskMemRealloc)
DEBUGWRAP8(CoTreatAsClass)
DEBUGWRAP0_NORET(CoUninitialize)
NODEF_DEBUGWRAP0(CoUnloadingWOW)
DEBUGWRAP8(CoUnmarshalHresult)
DEBUGWRAP12(CoUnmarshalInterface)
DEBUGWRAP4(CreateAntiMoniker)
DEBUGWRAP8(CreateBindCtx)
DEBUGWRAP4(CreateDataAdviseHolder)
DEBUGWRAP16(CreateDataCache)
DEBUGWRAP8(CreateFileMoniker)
DEBUGWRAP12(CreateGenericComposite)
DEBUGWRAP12(CreateILockBytesOnHGlobal)
DEBUGWRAP12(CreateItemMoniker)
DEBUGWRAP4(CreateOleAdviseHolder)
DEBUGWRAP8(CreatePointerMoniker)
DEBUGWRAP12(CreateStreamOnHGlobal)
NODEF_DEBUGWRAP0(DllDebugObjectRPCHook)
NODEF_DEBUGWRAP12(OLE32_DllGetClassObject)
NODEF_DEBUGWRAP0(DllGetClassObjectWOW)
DEBUGWRAP16(DoDragDrop)
NODEF_DEBUGWRAP0(EnableHookObject)
DEBUGWRAP8(GetClassFile)
NODEF_DEBUGWRAP4(GetConvertStg)
NODEF_DEBUGWRAP0(GetDocumentBitStg)
DEBUGWRAP8(GetHGlobalFromILockBytes)
NODEF_DEBUGWRAP8(GetHGlobalFromStream)
NODEF_DEBUGWRAP0(GetHookInterface)
DEBUGWRAP8(GetRunningObjectTable)
DEBUGWRAP16(IsAccelerator)
#undef IsEqualGUID
NODEF_DEBUGWRAP8(IsEqualGUID)
NODEF_DEBUGWRAP4(IsValidIid)
DEBUGWRAP4(IsValidInterface)
NODEF_DEBUGWRAP4(IsValidPtrIn)
NODEF_DEBUGWRAP4(IsValidPtrOut)
NODEF_DEBUGWRAP16(MkParseDisplayName)
DEBUGWRAP12(MonikerCommonPrefixWith)
NODEF_DEBUGWRAP16(MonikerRelativePathTo)
NODEF_DEBUGWRAP0(OleBuildVersion)
NODEF_DEBUGWRAP8(OleConvertIStorageToOLESTREAM)
NODEF_DEBUGWRAP28(OleConvertIStorageToOLESTREAMEx)
NODEF_DEBUGWRAP12(OleConvertOLESTREAMToIStorage)
NODEF_DEBUGWRAP28(OleConvertOLESTREAMToIStorageEx)
DEBUGWRAP28(OleCreate)
DEBUGWRAP16(OleCreateDefaultHandler)
NODEF_DEBUGWRAP24(OleCreateEmbeddingHelper)
DEBUGWRAP28(OleCreateFromData)
DEBUGWRAP32(OleCreateFromFile)
DEBUGWRAP28(OleCreateLink)
DEBUGWRAP28(OleCreateLinkFromData)
DEBUGWRAP28(OleCreateLinkToFile)
DEBUGWRAP8(OleCreateMenuDescriptor)
DEBUGWRAP28(OleCreateStaticFromData)
DEBUGWRAP4(OleDestroyMenuDescriptor)
NODEF_DEBUGWRAP8(OleDoAutoConvert)
DEBUGWRAP16(OleDraw)
DEBUGWRAP12(OleDuplicateData)
DEBUGWRAP0(OleFlushClipboard)
NODEF_DEBUGWRAP8(OleGetAutoConvert)
DEBUGWRAP4(OleGetClipboard)
DEBUGWRAP12(OleGetIconOfClass)
NODEF_DEBUGWRAP8(OleGetIconOfFile)
DEBUGWRAP4(OleInitialize)
NODEF_DEBUGWRAP0(OleInitializeWOW)
DEBUGWRAP4(OleIsCurrentClipboard)
DEBUGWRAP4(OleIsRunning)
DEBUGWRAP16(OleLoad)
DEBUGWRAP12(OleLoadFromStream)
DEBUGWRAP12(OleLockRunning)
NODEF_DEBUGWRAP16(OleMetafilePictFromIconAndLabel)
NODEF_DEBUGWRAP8(OleNoteObjectVisible)
DEBUGWRAP4(OleQueryCreateFromData)
DEBUGWRAP4(OleQueryLinkFromData)
DEBUGWRAP12(OleRegEnumFormatEtc)
DEBUGWRAP8(OleRegEnumVerbs)
DEBUGWRAP12(OleRegGetMiscStatus)
DEBUGWRAP12(OleRegGetUserType)
DEBUGWRAP4(OleRun)
DEBUGWRAP12(OleSave)
DEBUGWRAP8(OleSaveToStream)
NODEF_DEBUGWRAP8(OleSetAutoConvert)
DEBUGWRAP4(OleSetClipboard)
DEBUGWRAP8(OleSetContainedObject)
DEBUGWRAP20(OleSetMenuDescriptor)
DEBUGWRAP12(OleTranslateAccelerator)
DEBUGWRAP0_NORET(OleUninitialize)
NODEF_DEBUGWRAP0(OpenOrCreateStream)
DEBUGWRAP8(ProgIDFromCLSID)
DEBUGWRAP8(ReadClassStg)
DEBUGWRAP8(ReadClassStm)
DEBUGWRAP12(ReadFmtUserTypeStg)
NODEF_DEBUGWRAP0(ReadOleStg)
NODEF_DEBUGWRAP0(ReadStringStream)
DEBUGWRAP8(RegisterDragDrop)
DEBUGWRAP4(ReleaseStgMedium)
DEBUGWRAP4(RevokeDragDrop)
DEBUGWRAP8(SetConvertStg)
NODEF_DEBUGWRAP0(SetDocumentBitStg)
DEBUGWRAP16(StgCreateDocfile)
DEBUGWRAP16(StgCreateDocfileOnILockBytes)
DEBUGWRAP4(StgIsStorageFile)
DEBUGWRAP4(StgIsStorageILockBytes)
DEBUGWRAP24(StgOpenStorage)
DEBUGWRAP24(StgOpenStorageOnILockBytes)
NODEF_DEBUGWRAP16(StgSetTimes)
DEBUGWRAP8(StringFromCLSID)
DEBUGWRAP12(StringFromGUID2)
NODEF_DEBUGWRAP0(UtConvertDvtd16toDvtd32)
NODEF_DEBUGWRAP0(UtConvertDvtd32toDvtd16)
NODEF_DEBUGWRAP0(UtGetDvtd16Info)
NODEF_DEBUGWRAP0(UtGetDvtd32Info)
DEBUGWRAP8(WriteClassStg)
DEBUGWRAP8(WriteClassStm)
DEBUGWRAP12(WriteFmtUserTypeStg)
NODEF_DEBUGWRAP0(WriteOleStg)
NODEF_DEBUGWRAP0(WriteStringStream)
DEBUGWRAP8(CoInitializeEx)
DEBUGWRAP24(CoCreateInstanceEx)
NODEF_DEBUGWRAP4(PropVariantClear)
DEBUGWRAP0(CoResumeClassObjects)
NODEF_DEBUGWRAP0(OLE32_DllRegisterServer)
NODEF_DEBUGWRAP4(CreateErrorInfo)
NODEF_DEBUGWRAP8(GetErrorInfo)
NODEF_DEBUGWRAP8(FreePropVariantArray)
NODEF_DEBUGWRAP8(PropVariantCopy)
NODEF_DEBUGWRAP8(SetErrorInfo)
DEBUGWRAP0(CoImpersonateClient)
DEBUGWRAP36(CoInitializeSecurity)
DEBUGWRAP4(CoRegisterSurrogate)
DEBUGWRAP8(WINE_StringFromCLSID)
DEBUGWRAP8(CLSIDFromStringA)
DEBUGWRAP8(CLSIDFromString16)


