<?php

$sMainDir = "../";

require "cvs.php3";
require $sMainDir."stilovi.php3";

/*
 * Parse argument(s)
 */
if (isset($sFile))
{
    if (isset($sRevision))
    {
        $sOperation = "viewfile";
        if ($sRevision == "HEAD")
            $sRevision = "";
        $sTitle = substr($sFile, 0, -2)."\nrev.: ". ($sRevision == "" ? "HEAD" : $sRevision);
    }
    else
    {
        $sOperation = "viewfileinfo";
        $sTitle = substr($sFile, 0, -2);
    }
}
else if (isset($sDir))
{
    $sOperation = "viewdir";
    $sTitle = ($sDir == "." || $sDir =="") ? "./" : $sDir."/";
    $iSortColumn = (!isset($iSortColumn) || $iSortColumn == "")  ?
                        0 : $iSortColumn = @(int)$iSortColumn;
}
else
{   /* default action: */
    $sOperation = "viewdir";
    $sDir = ".";
    $sTitle = "root";
    $iSortColumn = 0;
}


/*
 * Odin32 look.
 */
require $sMainDir."01-PreTitle.php3";
echo "Odin32 CVS: ", str_replace("\n", " ", $sTitle);
require $sMainDir."02-PostTitle.php3";

require $sMainDir."03-MainTableBeg.php3";
require $sMainDir."04-ColumnOne.php3";

require $sMainDir."05-ColumnTwoHeader.php3";
echo "Odin32 CVS: ", str_replace("\n", "<br>", $sTitle);
require $sMainDir."06-ColumnTwoHeader2.php3";


/*
 *
 */
flush();

/*
 * Do the requested operation...
 */
switch ($sOperation)
{

    case "viewfileinfo":
    {
        $obj = new CVSFile($sFile, 0);
        if ($obj && $obj->fOk)
        {
            if (!$obj->PrintAllInfo())
            {
                echo "<p><i>PrintRevision failed.</i>";
                echo "<br><i>".$obj->sError."<br>";
            }
        }
        else
        { //error - complain
            echo "<p><i>An error occured while creating file object for $sFile.</i>";
            if ($obj)
                echo "<br><i>".$obj->sError."<br>";
        }
        break;
    }

    case "viewfile":
    {
        $obj = new CVSFile($sFile, 0);
        if ($obj && $obj->fOk)
        {
            if (!$obj->PrintRevision($sRevision))
            {
                echo "<p><i>PrintRevision failed.</i>";
                echo "<br><i>".$obj->sError."<br>";
            }
        }
        else
        { //error - complain
            echo "<p><i>An error occured while creating file object for $sFile.</i>";
            if ($obj)
                echo "<br><i>".$obj->sError."<br>";
        }
        break;
    }


    case "viewdir":
    {
        ListDirectory($sDir, $iSortColumn);
        break;
    }

    default:
        echo "IPE";
}


/*
 * Finish off the column
 */
require $sMainDir."07-ColumnTwoFooter.php3";

if (1)
{
    require $sMainDir."08-News.php3";
    /*
    require $sMainDir."09-ContentsTitle.php3";

    TocBeg();
    TocEnd();

    */
    require $sMainDir."10-EndOfContent.php3";
    require $sMainDir."11-NetlabsContact.php3";

    $Kada=date ("j M Y", filemtime(__file__));
    require $sMainDir."12-OdinBanner.php3";
}
else
{
    echo "</td>\n</tr></table>\n";
    echo "</td>\n</tr></table>\n";
}
require $sMainDir."13-Closing.php3";


?>
