<?php

$sMainDir = "../";

require $sMainDir."stilovi.php3";
require "Odin32DBHelpers.php3";

$sTitle = "The Odin32 PE Loaders";

require $sMainDir."01-PreTitle.php3";
echo $sTitle;
require $sMainDir."02-PostTitle.php3";

require $sMainDir."03-MainTableBeg.php3";
require $sMainDir."04-ColumnOne.php3";

require $sMainDir."05-ColumnTwoHeader.php3";
echo $sTitle;
require $sMainDir."06-ColumnTwoHeader2.php3";


/*
 * The article
 */

echo "
    The story of the program being executed.
";

TekstBeg();
echo "

    It all started when I typed the name of the program on an OS/2 commandline.
    This program was a not a native OS/2 program, as you might has thougth, but
    a Win32 program called SOL.EXE, or Solitaire. The first thing that happend
    was that the Shell, which in my case is 4OS/2, asks the Kernel what type of
    application this is. Some Programs are Presentation Manager programs, other
    are VIO (Virtual I/O) programs, while others again are pure full screen
    programs. So, 4OS/2 needs to know what kindred the program belongs to in
    order to start it in it's corrected environment.
<p>
    DosQueryAppType is the name of the API telling which type a program has.
    This 32-bit call thunks to the 16-bit DosQAppType which does. DosQAppType
    checks if the specified programname has a path. If is has a (absolute) path
    nothing extra is done to find the file. But, if it hasn't the PATH is
    searched. If not found the .EXE extention is eventually (if not present)
    added to the filename and the PATH is researched. Then the Kernel is
    called, DOSIQAPPTYPE. DOSIQAPPTYPE does a farcall to w_QAppType which in
    turn thunks to the 32-bit loader function LDRQAppType. (Note that the
    LDR-prefix is in capital letters. This could be understood as this is an
    officially exported function from the Loader subsystem.
<p>



";
TekstEnd();





/*
 * Standard stuff.
 */

require $sMainDir."07-ColumnTwoFooter.php3";
require $sMainDir."08-News.php3";
require $sMainDir."09-ContentsTitle.php3";

Odin32DBWriteContents();

require $sMainDir."10-EndOfContent.php3";
require $sMainDir."11-NetlabsContact.php3";

$Kada=date ("j M Y", filemtime(__file__));
require $sMainDir."12-OdinBanner.php3";

require $sMainDir."13-Closing.php3";




?>
