<?php
$Naziv="Project Odin Miscellaneous Guidelines";

$sMainDir = "../";

require $sMainDir."stilovi.php3";
require "Odin32DBHelpers.php3";

/* Profiling */
$sPageTimer = Odin32DBTimerStart("page timer");
/* Profiling */


require $sMainDir."01-PreTitle.php3";
echo $Naziv;
require $sMainDir."02-PostTitle.php3";

require $sMainDir."03-MainTableBeg.php3";
require $sMainDir."04-ColumnOne.php3";

require $sMainDir."05-ColumnTwoHeader.php3";
echo $Naziv;
require $sMainDir."06-ColumnTwoHeader2.php3";


/*
 * Introduction
 */
TekstBeg();
echo "
        Collections of miscellaneous guidelines recommended
        used in Project Odin.
        ";
TekstEnd();


/*
 * Date And Time
 */
Odin32DBNaslov("Date And Time","datetime");
TekstBeg();
echo "
        We will try use the ISO date and time format whenever giving
        dates and times. This will avoid Y2K problems and misunderstandings
        due to national date or time formats.
        <p>

        <dl>
            <dt><b>YYYY-MM-DD</b>
         <dd><b>Y</b> = Year, <b>M</b> = Month, <b>D</b> = Day.
            <dt><b>HH:MM:SS</b>
            <dd><b>H</b> = Hour, <b>M</b> = Minute, <b>S</b> = Second
        </dl>

        ";
TekstEnd();


require $sMainDir."07-ColumnTwoFooter.php3";
require $sMainDir."08-News.php3";
require $sMainDir."09-ContentsTitle.php3";

Odin32DBWriteContents();

require $sMainDir."10-EndOfContent.php3";
require $sMainDir."11-NetlabsContact.php3";

$Kada=date ("j M Y", filemtime(__file__));
require $sMainDir."12-OdinBanner.php3";

require $sMainDir."13-Closing.php3";

/* Profiling */
Odin32DBTimerStop($sPageTimer);
/* Profiling */

?>
