<?php
$Naziv="Project Odin Guidelines";

$sMainDir = "../";

require $sMainDir."stilovi.php3";
require "Odin32DBHelpers.php3";

/* Profiling */
$sPageTimer = Odin32DBTimerStart("page timer");
/* Profiling */


require $sMainDir."01-PreTitle.php3";
echo $Naziv;
require $sMainDir."02-PostTitle.php3";

require $sMainDir."03-MainTableBeg.php3";
require $sMainDir."04-ColumnOne.php3";

require $sMainDir."05-ColumnTwoHeader.php3";
echo $Naziv;
require $sMainDir."06-ColumnTwoHeader2.php3";


/*
 * Introduction
 */
TekstBeg();
echo "
        On this page we list the guidelines currently available for the Odin
        project. The guidelines addresses different aspects of the development
        which we should try do in the same way. <p>

        When a guideline is accepted you should read it and follow it.<p>

        Currently none of the guidelines are accepted (but this will
        change soon). It will probably not cause any harm to reading and use the
        guidelines before they are accepted, but some changes should be expected.
        ";
TekstEnd();


/*
 * Source Code Documentation Guidelines
 */
Odin32DBNaslov("Source Code Documentation Guidelines","SCDG");
TekstBeg();
echo "
        The Source Code Documentation Guidelines describes how to document
        your source code. Documenting the source code is helpful when
        we're to maintain and extend the code later. We also use the
        source code documentation to keep track of the progess. This done by
        keeping a state with each API implementation. The source code
        documentation is read after each daily build and is made available
        on the ";
LocLink("Odin32DB.phtml", "Odin32 API Database");
echo   " pages.<p>
        ";

LocLink("Odin32GuidelineDocumentation.phtml", "Source Code Documentation Guidelines");
echo " - <tt>proposal IV</tt>
        ";
TekstEnd();


/*
 * Coding Guidelines
 */
 /*
Odin32DBNaslov("Coding Guidelines","codingg");
TekstBeg();
echo "

        ";

LocLink("Odin32GuidelineCoding.phtml", "Coding Guidelines");
echo " - <tt>draft</tt>
        ";
TekstEnd();
 */

/*
 * Miscellaneous Guidelines.
 */
Odin32DBNaslov("Miscellaneous Guidelines","miscg");
TekstBeg();
echo "
        Collections of short guidelines.<p>
        ";

LocLink("Odin32GuidelineMisc.phtml", "Miscellaneous Guidelines");
echo " - <tt>draft</tt>
        ";
TekstEnd();




require $sMainDir."07-ColumnTwoFooter.php3";
require $sMainDir."08-News.php3";
require $sMainDir."09-ContentsTitle.php3";

Odin32DBWriteContents();

require $sMainDir."10-EndOfContent.php3";
require $sMainDir."11-NetlabsContact.php3";

$Kada=date ("j M Y", filemtime(__file__));
require $sMainDir."12-OdinBanner.php3";

require $sMainDir."13-Closing.php3";

/* Profiling */
Odin32DBTimerStop($sPageTimer);
/* Profiling */

?>
