<?php
$Naziv="Teams Working on Project Odin";

$sMainDir = "../";

require $sMainDir."stilovi.php3";
require "Odin32DBHelpers.php3";
require "Odin32DBConnect.php3";

require $sMainDir."01-PreTitle.php3";
echo $Naziv;
require $sMainDir."02-PostTitle.php3";

require $sMainDir."03-MainTableBeg.php3";
require $sMainDir."04-ColumnOne.php3";

require $sMainDir."05-ColumnTwoHeader.php3";
echo $Naziv;
require $sMainDir."06-ColumnTwoHeader2.php3";


TekstBeg();
echo "
        In order to better coordinate development, project members are
        organized into teams that take care of specific issues, both
        those that are tied to development and those relevant to
        'supporting activities'. Each team has a separate mailing list
        that it uses for coordination of activities. The WAI Team
        (Win32 API Implementation), largest of all, has several groups
        that cover separate sets of API functions. <p>

        Teams working on Project Odin are:
     ";
TekstEnd();




$sSql ="SELECT\n".
       "    refcode,\n".
       "    name,\n".
       "    longname,\n".
       "    description,\n".
       "    tasks,\n".
       "    notes\n".
       "FROM\n".
       "    team\n".
       "ORDER BY refcode\n";
$Result = mysql_query($sSql, $db);
if (!$Result)
{
    Odin32DBSqlError($sSql);
    die("Failed to query teams from database!");
}

/*
 * Loop thru all teams and display information about each.
 */
while ($aTeam = mysql_fetch_array($Result))
{
    Odin32DBNaslov2($aTeam["name"]." Team<br><font size=-1>(".$aTeam["longname"].")</font>",
                    $aTeam["name"]." Team<br><i>(".$aTeam["longname"].")</i>",
                    $aTeam["name"]);
    /*
     * Description
     */
    TekstBeg();
    echo $aTeam["description"]."<p>\n";
    TekstEnd();


    /*
     * If more than one group list them!
     */
    $sSql ="SELECT\n".
           "    refcode,\n".
           "    name,\n".
           "    description,\n".
           "    notes\n".
           "FROM\n".
           "    tgroup\n".
           "WHERE\n".
           "    team = ".$aTeam["refcode"]."\n".
           "ORDER By refcode\n";
    $Result2 = mysql_query($sSql, $db);
    if (!$Result2)
    {
        echo "<tr><td>";
        Odin32DBSqlError($sSql);
        echo "</td></tr></table></table></table>";
        die("team group sql failed");
    }
    $cGroups = mysql_num_rows($Result2);
    if ($cGroups > 1)
    {
        TekstBeg();
        echo "The ".$aTeam["name"]." Team consists of following groups with\n".
             "accompanying tasks:";
        TekstEnd();

        GrayTableBeg("");
        echo "<TR>";
        GTCell("Group", "WIDTH=30% VALIGN=middle align=center", "d0d0d0");
        GTCell("Task",  "WIDTH=70% VALIGN=middle align=center", "d0d0d0");
        echo "</TR>";

        while ($aGroup = mysql_fetch_array($Result2))
        {
            echo "<TR>";
            GTCell($aGroup["name"], "VALIGN=middle", "");
            GTCell($aGroup["description"], "", "");
            echo "</TR>";
        }
        GrayTableEnd();

        if ($aTeam["name"] == 'WAI')
        {
            TekstBeg();
            echo "\n".
                 "   More detailed informations about each group's status and progress is available from\n";
            LocLink("DevelopersOdin32WAI.phtml", "'Odin32 API' pages in 'Developers' section");
            echo ".<p>\n";
            TekstEnd();
        }
    }


    /*
     * List task, members, and notes table
     */
    TableBeg("");

    /*
     * tasks
     */
    if (isset($aTeam["tasks"]))
    {
        echo "<tr>\n";
        TCell("<b>Tasks:</b>", "width=20% valign=top align=right");
        TCell($aTeam["tasks"], "width=80%");
        echo "</tr>\n",
             "<tr><td colspan=2> &nbsp; </td></tr>\n";
    }

    /*
     * members
     */
    $sSql ="SELECT DISTINCT\n".
           "    a.name      AS name,\n".
           "    a.email     AS email\n".
           "FROM\n".
           "    tgroup,\n".
           "    tgroupmember,\n".
           "    author a\n".
           "WHERE\n".
           "    tgroup.team = ".$aTeam["refcode"]."    AND\n".
           "    tgroupmember.tgroup = tgroup.refcode   AND\n".
           "    MOD(tgroupmember.tgroup, 1000) <> 999  AND\n". //Ignore the unassigned group (ends with 999).
           "    a.refcode = tgroupmember.author\n".
           "ORDER BY codemaintainer DESC, last, name\n";
    $Result2 = mysql_query($sSql, $db);
    if (!$Result2)
    {
        echo "<tr><td>";
        Odin32DBSqlError($sSql);
        echo "</td></tr></table></table></table>";
        die("team member sql failed");
    }
    if (mysql_num_rows($Result2) > 0)
    {
        $sMembers = "";
        while ($aMember = mysql_fetch_array($Result2))
            $sMembers = $sMembers."<li> ".
                        (isset($aMember["email"])
                            ? "<a href=\"mailto:".$aMember["email"]."\">". $aMember["name"]."</a>\n"
                            : $aMember["name"]."\n");

        echo "<tr>\n";
        TCell("<b>Members:</b>", "width=20% valign=top align=right");
        TCell($sMembers, "width=80%");
        echo "</tr>\n",
             "<tr><td colspan=2> &nbsp; </td></tr>\n";
    }

    /*
     * Unassigned members if $cGroups > 1
     */
    if ($cGroups > 1)
    {
        $sSql ="SELECT DISTINCT\n".
               "    a.name      AS name,\n".
               "    a.email     AS email\n".
               "FROM\n".
               "    tgroup,\n".
               "    tgroupmember,\n".
               "    author a\n".
               "WHERE\n".
               "    tgroup.team = ".$aTeam["refcode"]."  AND\n".
               "    tgroupmember.tgroup = tgroup.refcode AND\n".
               "    MOD(tgroupmember.tgroup, 1000) = 999   AND\n". //Only the unassigned group (ends with 999).
               "    a.refcode = tgroupmember.author\n".
               "ORDER BY last, name\n";
        $Result2 = mysql_query($sSql, $db);
        if (!$Result2)
        {
            echo "<tr><td>";
            Odin32DBSqlError($sSql);
            echo "</td></tr></table></table></table>";
            die("team member sql failed");
        }
        if (mysql_num_rows($Result2) > 0)
        {
            $sMembers = "<i>";
            while ($aMember = mysql_fetch_array($Result2))
                $sMembers = $sMembers."<li> ".
                            (isset($aMember["email"])
                                ? "<a href=\"mailto:".$aMember["email"]."\">". $aMember["name"]."</a>\n"
                                : $aMember["name"]."\n");

            echo "<tr>\n";
            TCell("<b>Unassigned:</b>", "width=20% valign=top align=right");
            TCell($sMembers."</i>", "width=80%");
            echo "</tr>\n",
                 "<tr><td colspan=2> &nbsp; </td></tr>\n";

            /* note if WAI */
            if ($aTeam["name"] == "WAI")
            {
                TableEnd();
                TekstBeg("");
                echo "\n".
                     "   <i>Unassigned</i> members are listed in italic. Detailed\n".
                     "   information about each member's assignment is available from <a\n".
                     "   href=DevelopersOdin32API.phtml>Odin32 API pages in 'Developers'\n".
                     "   section</a>.<p>\n";
                TekstEnd();
                TableBeg("");
            }
        }
    }


    /*
     * notes
     */
    if (isset($aTeam["notes"]))
    {
        echo "<tr>\n";
        TCell("<b>Notes:</b>", "width=20% valign=top align=right");
        TCell($aTeam["notes"], "width=80%");
        echo "</tr>\n",
             "<tr><td colspan=2> &nbsp; </td></tr>\n";
    }

    /* end of task, members, notes table */
    TableEnd();

}



require $sMainDir."07-ColumnTwoFooter.php3";
require $sMainDir."08-News.php3";
require $sMainDir."09-ContentsTitle.php3";
Odin32DBWriteContents();
require $sMainDir."10-EndOfContent.php3";
require $sMainDir."11-NetlabsContact.php3";

$Kada=date ("j M Y", filemtime(__file__));
require $sMainDir."12-OdinBanner.php3";

require $sMainDir."13-Closing.php3";
?>
