## @file
#

SUB_DEPTH = ../../..
include $(KBUILD_PATH)/subheader.kmk

PROGRAMS               += GuardPages
GuardPages_TEMPLATE     = OdinTestApp
GuardPages_SOURCES      = main.cpp
GuardPages_LIBS         = $(PATH_STAGE_LIB)/kernel32.lib

include $(FILE_KBUILD_SUB_FOOTER)
