## @file
# OLEDLG library
#

SUB_DEPTH = ../..
include $(KBUILD_PATH)/subheader.kmk

$(call odin_implib,oledlg)

DLLS               += oledlg
oledlg_TEMPLATE     = OdinSimpleDLL

oledlg_SOURCES      = \
    oledlg.cpp \
    oledlgrsrc.orc \
    oledlg.def

oledlg_LIBS         = \
    $(PATH_STAGE_LIB)/kernel32.lib

include $(FILE_KBUILD_SUB_FOOTER)
