#ifndef __SHELLICON_H__
#define __SHELLICON_H__

#define SHLICON_FILE			0
#define SHLICON_TEXTFILE		1
#define SHLICON_APPLICATION		2
#define SHLICON_FOLDER_CLOSED	3
#define SHLICON_FOLDER_OPEN		4
#define SHLICON_FLOPPY525		5
#define SHLICON_FLOPPY35		6
#define SHLICON_REMOVABLE_DISK	7
#define SHLICON_HARDDISK		8
#define SHLICON_NETDRIVE_CONN   9
#define SHLICON_NETDRIVE_DISCON 10
#define SHLICON_CDROM_DRIVE		11
#define SHLICON_RAMDRIVE		12
#define SHLICON_ENTIRENETWORK	13
#define SHLICON_NETWORK			14
#define SHLICON_NETWORK_COMP	15
#define SHLICON_PRINTER			16
#define SHLICON_NETWORK_PLACE	17
#define SHLICON_NETWORK_GROUP	18
#define SHLICON_PROGRAMS		19
#define SHLICON_RECENTDOCS		20
#define SHLICON_SETTINGS		21
#define SHLICON_SEARCH			22
#define SHLICON_HELP			23
#define SHLICON_RUN				24
#define SHLICON_SUSPEND			25
#define SHLICON_UNDOCK			26
#define SHLICON_SHUTDOWN		27
#define SHLICON_SHAREDRES		28
#define SHLICON_SHORTCUT		29
#define SHLICON_ARROW			30
#define SHLICON_TRASHCAN		31
#define SHLICON_TRASHCAN_FULL	32
#define SHLICON_DIALUP_FOLDER	33
#define SHLICON_DESKTOP			34
#define SHLICON_CONTROLPANEL	35
#define SHLICON_PROGRAMGROUP	36
#define SHLICON_PRINTER_FOLDER	37
#define SHLICON_FONT_FOLDER     38
#define SHLICON_LOGO			39
#define SHLICON_AUDIO_CD		40
#define SHLICON_TREE			41
#define SHLICON_COMPUTERS		42
#define SHLICON_FAVORITES		43
#define SHLICON_LOGOFF			44

//is actually present in explorer.exe..
#define SHLICON_MYCOMPUTER      999

#endif //__SHELLICON_H__
