## @file
# LIBWRAP library
#

SUB_DEPTH = ../..
include $(KBUILD_PATH)/subheader.kmk

LIBRARIES          += libwrap
libwrap_TEMPLATE    = OdinCxx
libwrap_SOURCES    := $(wildcard $(PATH_SUB_CURRENT)/*.asm)

include $(FILE_KBUILD_SUB_FOOTER)
