## @file
# MSVCRT library
#

SUB_DEPTH = ../..
include $(KBUILD_PATH)/subheader.kmk

LIBRARIES          += minivcrt
minivcrt_TEMPLATE  = OdinCxx

minivcrt_DEFS      = __MINIVCRT__

minivcrt_SOURCES   = \
    dir.c \
    environ.c \
    errno.c \
    file.c \
    wcs.c

include $(FILE_KBUILD_SUB_FOOTER)
