## @file
# Support tools
#

SUB_DEPTH = ..
include $(KBUILD_PATH)/subheader.kmk

#
# Include sub-makefiles.
#
include $(PATH_SUB_CURRENT)/common/Makefile.kmk
include $(PATH_SUB_CURRENT)/impdef/Makefile.kmk
include $(PATH_SUB_CURRENT)/wrc/Makefile.kmk
include $(PATH_SUB_CURRENT)/install/Makefile.kmk

include $(FILE_KBUILD_SUB_FOOTER)
